# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-JiRUo1QTNvUJWXlLJ4z78NKqT-5zWj
"""

a=2
b=3
print(a+b)