# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIqFi9jla_X2CrCWIsKKKxo9y9I6o522
"""

n=3
print(n*n)